openapi: 3.0.0
info:
  description: GUI API
  version: '1.0'
  title: gui
servers:
  - url: /gui/api/v1

security:
  - JWT: []

paths:
  /app/info:
    get:
      tags:
        - login
      summary: information about the current app
      operationId: appInformation
      responses:
        200:
          description: the app information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppInformation'
  /app/current-user:
    get:
      tags:
        - login
      summary: load current user from security context
      operationId: currentUser
      parameters:
        - in: header
          name: "X-Refresh-Token"
          schema:
            type: string
      responses:
        200:
          description: The user logged in
          content:
            application/json:
              schema:
                $ref: '../../../../../../apis/official-gui-api/openapi/v1.yaml/#/components/schemas/User'
        404:
          description: No user logged in
  /tasklist/usertask/{userTaskId}:
    get:
      tags:
        - tasklist
      summary: Fetch data of one single User task
      operationId: getUserTask
      parameters:
        - in: path
          name: userTaskId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Users task
          content:
            application/json:
              schema:
                $ref: '../../../../../../apis/official-gui-api/openapi/v1.yaml/#/components/schemas/UserTask'
        404:
          description: Unknown user task
  /tasklist/usertask:
    post:
      tags:
        - tasklist
      summary: User tasks to be shown in a list view
      operationId: getUserTasks
      parameters:
        - in: query
          name: pageNumber
          schema:
            type: integer
            format: int32
        - in: query
          name: pageSize
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Users tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTasks'
    put:
      tags:
        - tasklist
      summary: Updated list of usertasks
      operationId: getUserTasksUpdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserTasksUpdate"
      responses:
        200:
          description: Users tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTasks'
components:
  schemas:
    AppInformation:
      type: object
      required:
        - titleShort
        - titleLong
        - version
      properties:
        titleShort:
          type: string
        titleLong:
          type: string
        homepageUrl:
          type: string
        homepageServiceConditionsUrl:
          type: string
        contactEmailAddress:
          type: string
        version:
          type: string
    Page:
      type: object
      required:
        - totalElements
        - totalPages
        - number
        - size
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
    UserTasks:
      type: object
      required:
        - serverTimestamp
        - page
        - userTasks
      properties:
        serverTimestamp:
          type: string
          format: date-time
        page:
          $ref: '#/components/schemas/Page'
        userTasks:
          type: array
          items:
            $ref: '../../../../../../apis/official-gui-api/openapi/v1.yaml/#/components/schemas/UserTask'
    PingEvent:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    UserTaskEvent:
      type: object
      required:
        - id
        - name
        - type
      properties:
        type:
          type: string
        name:
          type: string
        id:
          type: string
    UserTasksUpdate:
      type: object
      required:
        - size
        - knownUserTasksIds
      properties:
        size:
          type: integer
          format: int32
        knownUserTasksIds:
          type: array
          items:
            type: string
