spring:
  data:
    mongodb:
      uri: mongodb://business-cockpit:business-cockpit@business-cockpit-mongo:27017/business-cockpit

bpms-api:
  username: abc
  password: "{noop}123"

business-cockpit:
  title-short: VanillaBP-BC
  title-long: VanillaBP Business Cockpit
  application-version: "@project.version@"
  application-uri: http://localhost:8080
