logging:
  level:
    ROOT: INFO

spring:
  application:
    name: VanillaBP-business-cockpit
  webflux:
    static-path-pattern: "/**"
  resources:
    static-locations: "classpath:/static/"

bpms-api:
  realm-name: BPMS-API