name: Publish to GitHub Packages
on:
  push:
    branches:
      - feature/deploy-to-github-packages
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@vanillabp'
          always-auth: true
      - uses: actions/delete-package-versions@v4.1.1
        with: 
          package-name: 'bc-official-gui-client'
          package-type: 'npm'
          min-versions-to-keep: 0
          ignore-versions: '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$'
      - uses: actions/delete-package-versions@v4.1.1
        with: 
          package-name: 'bc-shared'
          package-type: 'npm'
          min-versions-to-keep: 0
          ignore-versions: '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$'
      - uses: actions/delete-package-versions@v4.1.1
        with: 
          package-name: 'bc-dev-shell'
          package-type: 'npm'
          min-versions-to-keep: 0
          ignore-versions: '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$'
      - name: Publish package
        run: mvn --batch-mode deploy -Dnpm.registry=https://npm.pkg.github.com/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_userconfig: ${{ github.workspace }}/.npmrc
          CI: false
